### ISSUE TITLE
Events example error regarding keysyms for certain keys

### ISSUE THREAD

**Issue by dys-bigwig** [lockie/racket-sdl2#2]
Hi there. I understand the example is a direct translation (https://github.com/lockie/racket-sdl2/blob/master/examples/events.rkt) but I can't figure out how to work around this issue in general I'm afraid.
When testing events, attempting to get the keysym for some keys - the up arrow for example - yields the following error:
`enum:int->_SDL_Keycode: expected a known #<ctype:int32>, got: 1073741906
  context...:
   SDL_Keysym-sym
`
this error is a bit baffling to me, as I believe that number fits quite comfortably in an int32. For most keys (letters, numbers..) it works fine, but all the arrow keys seem to respond this way. I can use scancodes instead, but I have keys remapped (Caps-Lock to Esc for example) so unfortunately it's not always an ideal substitute.

Thank you.

**Comment by lockie** [comment]
Hello!
The aforementioned example works for me. Are you sure you're using the latest version of racket-sdl2?
To get the keysym, you should use `(SDL_KeyboardEvent-keysym (union-ref event 4))`, assuming that `event` holds `SDL_KeyboardEvent` value; `4` is numeric code for that. Then you can access [`SDL_Keysym` struct](https://wiki.libsdl.org/SDL_Keysym) fields using corresponding accessors, e.g. `SDL_Keysym-sym`.
Do you mind sharing your code so that I can further assist with your problem?

**Comment by dys-bigwig** [comment]
Hello, thank you very much for your quick response :)

This is rather strange; I'm just running the example verbatim and getting that error. I have the "events.rkt" file saved (along with the spaceship image) and running as usual via "racket events.rkt" on the command line. The mouse scrolling (changing the x and y positions in the title) work fine as well as left/right click, and most keys (letters/numbers) don't produce an error when pressed. As far as I can tell it's just the arrow keys, shift, ctrl, alt, numpad and function keys that all produce the same `#<ctype:int32>` error.

I thought perhaps the version being installed via "raco pkg install sdl" was outdated, so I installed directly from git "raco pkg install https://github.com/lockie/racket-sdl2.git" but sadly I still get the error.

Any ideas what could be going wrong? If I can provide any more information please let me know. Hopefully this isn't just a case of me making a silly error, but I'm just running the example without changes, so I'm not sure what that could be. My keyboard works fine and produces the expected keys, so I'm certain it's not a problem with my keyboard hardware/drivers/mapping or anything like that.

Thank you.

**Comment by lockie** [comment]
Yeah, that's weird, on my machine the example runs just fine with arrow keys.
Which racket version do you have?

**Comment by dys-bigwig** [comment]
I'm using racket 7.5.

**Comment by lockie** [comment]
All right, I've tested the example with 7.5 and it still works. Which version of SDL libraries and which OS are you using? Is it 64bit?

**Comment by dys-bigwig** [comment]
Hi, sorry about the delayed response.
Here's my SDL versions:
* libsdl1.2: 1.2.15+dfsg2-0.1ubuntu0.1
* libsdl2-2.0-0: 2.0.8+dfsg1-1ubuntu1.18.04.4

and my system is 32-bit.

Thank you.

**Comment by lockie** [comment]
Hey, no problem.

> and my system is 32-bit.

Oh, I feel like this should be the source of the problem. I'll find some time one of these days to setup 32bit virtual machine and check it out.

**Comment by lockie** [comment]
It seems to me like the upstream problem. I've reported it, let's wait for some answers.

**Comment by lockie** [comment]
@dys-bigwig Can you please install racket from latest git checkout and test whether the issue is gone?
