### ISSUE TITLE
SDL_Vulkan_GetInstanceExtensions 

### ISSUE THREAD

**Issue by raydialow** [lockie/racket-sdl2#3]
Any attempt to give SDL_Vulkan_GetInstanceExtensions three arguments results in 
```
arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  given: 3
  arguments...:
```
SDL_Vulkan_GetInstanceExtensions is `define-sdl2`'d [here](https://github.com/lockie/racket-sdl2/blob/ef380f86bfb41ad50b12caa278a501854647e84a/main.rkt#L2308) to take three arguments. [As it should be.](https://wiki.libsdl.org/SDL_Vulkan_GetInstanceExtensions)

I installed sdl2 with the DrRacket package manager. No import issues to speak of. Using DrRacket on latest CentOS. x86_64. SDL2 version 2.0.10.

**Comment by raydialow** [comment]
Ah, and the two arguments SDL_Vulkan_GetInstanceExtensions *is taking* are: the first (an `SDL_Window*`) and the second (a `uint*`.

**Comment by raydialow** [comment]
I've downloaded a copy of the master repo and imported directly from that. Calling SDL_Vulkan_GetInstanceExtensions without arguments gives the following error now:
```
...-master/main.rkt:2308:46: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  given: 0
```
The line referenced there, is the line:
```
(define-sdl2 SDL_Vulkan_GetInstanceExtensions (_fun _SDL_Window* _uint* (_ptr o _string) -> _SDL_bool)
    #:make-fail make-not-available)
```
Which clearly shows three arguments to a function returning _SDL_bool???

**Comment by raydialow** [comment]
Another test with all the types the problem procedure should expect:
new-sdl2-window is a procedure that simply initializes SDL and returns a window.
```
> (define sdlwindow* (new-sdl2-window))
> (define uint* (malloc 'raw _uint32))
> (cpointer-push-tag! uint* 'uint*)
> (define char** (malloc 'raw (_ptr o _string)))
> (SDL_Vulkan_GetInstanceExtensions sdlwindow*
                                    uint*
                                    char**)
. . ...-master/main.rkt:2308:46: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 2
  given: 3
  arguments...:
```

**Comment by raydialow** [comment]
Changing 
```
(define-sdl2 SDL_Vulkan_GetInstanceExtensions (_fun _SDL_Window* _uint* (_ptr o _string) -> _SDL_bool)
    #:make-fail make-not-available)
```
to
```
(define-sdl2 SDL_Vulkan_GetInstanceExtensions (_fun _SDL_Window* _uint* _pointer -> _SDL_bool)
    #:make-fail make-not-available)
```
corrects the arity issue, so I take it that `_fun` is not recognizing `(_ptr o _string)` as an argument.

Not a great solution I think as `_pointer` is probably not safest here?

**Comment by raydialow** [comment]
Ok, with the change from `(_ptr o _string)` to `_pointer` I can confirm that this now WORKS. If anyone has a better idea of how to do this, go ahead, but I'm going to close this, cuz, well, this works for me. 
```
(define (get-vulkan-extensions sdl2-window)
  (let ([extcount/p (malloc 'atomic _uint32)])
    (begin
      (cpointer-push-tag! extcount/p 'uint*)
      (SDL_Vulkan_GetInstanceExtensions sdl2-window extcount/p #f)
      (let ([extensions (malloc 'atomic _string (ptr-ref extcount/p _uint32))])
        (begin
          (SDL_Vulkan_GetInstanceExtensions sdl2-window extcount/p extensions)
          '(extcount/p extensions))))))
```
this snippet works to grab extensions list and count for to create a vkInstance...

**Comment by lockie** [comment]
Hey. Thanks for the working snippet!
Yeah, FFI in Racket could be a messy business.
I feel like perhaps `_ptr o` is wrong and I should've used `_ptr io`, as the former just allocates the pointer implicitly with malloc. I'm not actively using racket anymore, so any pull requests are welcome.
