### ISSUE TITLE
Unable to run on Macbook M1

### ISSUE THREAD

**Issue by LovingSalamander** [lockie/racket-sdl2#7]
SDL2 is installed on my system via homebrew, I installed with `raco pkg install sdl2` and I tried running `simple.rkt`, but I get the following error:

```
ffi-lib: could not load foreign library
  path: libSDL2-2.0.0.dylib
  system error: dlopen(libSDL2-2.0.0.dylib, 0x0006): tried: 'libSDL2-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file, not in dyld cache), 'libSDL2-2.0.0.dylib' (no such file), '/usr/lib/libSDL2-2.0.0.dylib' (no such file, not in dyld cache)
  context...:
   /Applications/Racket v8.10/collects/ffi/unsafe.rkt:131:0: get-ffi-lib
   body of "/Users/LovingSalamander/Library/Racket/8.10/pkgs/sdl2/main.rkt"
```

**Comment by lockie** [comment]
Hey, thanks for the report. Unfortunately I do not own Apple hardware, so I can only theorize here. It looks like Racket was not able to find the required dylib. Does the thing work if you try to link it to e.g. simple C "Hello SDL" program (say, [this one](https://gist.github.com/fschr/92958222e35a823e738bb181fe045274))?

**Comment by LovingSalamander** [comment]
Yeah, as long as I use sdl2-config to get the CFLAGS and LDFLAGS I can build C programs with SDL. So on my system, `sdl2-config --libs` gives `-L/opt/homebrew/lib -lSDL2`, which is where `libSDL2-2.0.0.dylib` is. I'm just unfamiliar with how racket's FFI works.

**Comment by lockie** [comment]
> I'm just unfamiliar with how racket's FFI works.

I haven't been using Racket in a while, so right now me too 😩 

Have you tried copying the dylib from homebrew to one of the directories mentioned in the error message?
